#!/bin/bash
#
# PropreDNS - Command line tool for managing DNS zones for BIND.
#
# Note: 'Propre' stands for Own in french.
#
# References:
# 1. http://www.thegeekstuff.com/2014/01/install-dns-server/
# 2. http://www.aboutdebian.com/dns.htm
#

# Do not change variables here, see /etc/default/pzone
force=false
ifname=eth0
me=$(basename $0)

## List of supported records
declare -a supported_records=(NS A MX CNAME TXT)
#declare -a supported_functions=(create_zone add_record publish_zone)

## Load defautls
[ -f "/etc/default/pzone" ] && . /etc/default/pzone

## Load user config
for conf in ~/.$me.conf ./$me.conf; do
    [ -f $conf ] && . $conf
done

## Input: warning message
## Output: none
## Return: true
function warn() {
    local message=$*
    echo -e "[$me]" ${message/\\n/\\n[$me] };
    return 0;
}

## Input: verbose message
## Output: none
## Return: true
function verbose() {
    local message=$*
    echo -e "[$me]" ${message/\\n/\\n[$me] };
    return 0;
}

## Input: error message
## Output: none
## Return: does not, exit with code 1
function die() {
    warn $*;
    exit 1;
}

## Input: bind zone file
## Output: serial number
## Return: true or false if bind file not found
function serial() {
    [ -f "$1" ] || return 1;
    local snum=$(awk '/Serial/ { print $1; }' $1);
    echo $snum
    return 0;
}

## Input: numbers of seconds.
## Output: human readable time.
function human() {
    local secs=$1;		# 604800
    local mins=$((secs/60));	# 10080, 0
    secs=$((secs-60*mins));
    local hours=$((mins/60));	# 168, 0
    mins=$((mins-60*hours));
    local days=$((hours/24));	# 7, 0
    hours=$((hours-24*days));
    [ "$days" -gt 0 ] && echo $days"d" && return 0;
    [ "$hours" -gt 0 ] && echo $hours"h" && return 0;
    [ "$mins" -gt 0 ] && echo $mins"m" && return 0;
    echo $secs"s";
    return 0;
}

## Input: Zone name
## Output: none
## Return: true or false is not present
function check_zone() {
    [ -z "$1" ] && die "check_zone():" Missing zone name;
    [ -d "$pzonedir/$1" ] && \
	[ -f "$pzonedir/$1/config" ] && return 0; # True
    return 1; # False
}

## Input: Record type
## Output: none
## Return: true or false is not a supported type
function check_rectype() {
    [ -z "$1" ] && die "check_rectype():" Missing type;
    for item in ${supported_records[*]}; do
	[ "$item" == "$1" ] && return 0; # True
    done
    return 1; # False
}

## Input: Zone name, record type, record name {, record priority}
## Output: none
## Return: true or false if record is not present
function check_record() {
    [ -z "$3" ] && die "check_zone():" Missing arguments;
    check_rectype $2 || die "check_record():" Unsupported record type: $2;
    check_zone $1 || die "check_record():" Zone not found: $1;
    [ -f "$pzonedir/$1/records.$2" ] || return 1; # False - no $2 records.
    local lookup="^$3,"
    [ -n "$4" ] && lookup="^$3,$4,";
    grep -qP $lookup $pzonedir/$1/records.$2 && return 0; # True
    return 1; # False
}

## Input: Zone name
## Output: none
## Return: true or false if record is not present
function update_serial() {
    [ -z "$1" ] && die "update_serial():" Missing arguments;
    check_zone $1 || die "update_serial():" Zone not found: $1;

    local snum0=$(serial "$binddir/db.$1");
    if [ -n "$snum0" ]; then
	local snum=$(date +%Y%m%d01)
	while [ $snum -le $snum0 ]; do snum=$((snum+1)); done
    else
	snum=$(date +%Y%m%d01)
    fi
    echo "serial="$snum > $pzonedir/$1/serial
}

## Input: Zone name, record type, record name, record params...
##        record params=(ALIAS|HOST|IPADDR|(PRIORITY MAILSERVER))
## Output: none
## Return: true
function add_record() {
    [ -z "$4" ] && die "add_record():" Missing arguments;
    [ "$2" == "MX" ] && [ -z "$5" ] && die "add_record():" Missing arguments;

    local zone=$1
    local type=$2
    local name=$3
    local parm=$4
    local prio=
    local errstr=
    local lookup=

    check_zone $zone || die "add_record():" Zone not found: $zone;
    check_rectype $type || die "add_record():" Unsupported record type: $type

    local records=$pzonedir/$zone/records.$type
    [ -f "$records" ] || touch $records;

    [ "$type" == "MX" ] && \
	prio=$4 && \
	parm=$5 && \
	lookup=",$4" && \
	errstr=", priority= $4";	# Update for MX record

    check_record $zone $type $name $prio && [ $force = false ] && \
	die "add_record():" Record $type already exist: $name$errstr;

    # Check assigned mail or name server, must exist local or external.
    if [ "$type" == "MX" ] || [ "$type" == "NS" ] || [ "$type" == "CNAME" ];
    then
	local required=

	# Part of my zone - full qualified
	if echo $parm | grep -qP "$zone$"; then
	    required=${parm/.$zone/};
	    parm=$parm.

	# Part of my zone - short name
	elif echo $parm | grep -qv '\.'; then
	    required=$parm;
	fi

	if [ -n "$required" ]; then
	    local found=$force
	    for item in A CNAME; do
		check_record $zone $item $required && found=true
	    done
	    $found || \
		die "Adding record $type, record A|CNAME not found: "$required \
		    "\nPlease define first!"

	else	# External host
	    $force || host $parm >/dev/null || \
		die "Adding record $type, host not found: $parm";
	    parm=$parm.
	fi
    fi

    sed -i "/$3,$lookup/d" $records	# Cleanup record, if any.
    echo $name $prio $parm | \
	sed 's/ /,/g' >> $records	# Add record
    update_serial $zone			# Update serial number

    verbose Record $name $type $parm added.

    return 0;
}

## Input: {verbose flag}
## Return: true or false if missing parameter(s)
function check_params() {
    local result=0;	# True
    for p in ttl refresh retry expire ncachettl; do
	[ -n "${!p}" ] && continue;
	result=1;	# False
	[ -z "$1" ] && continue;
	warn "Parameter not defined: "$p
    done
    return $result;
}

## Input: Zone name {Output file}
## Return: true
function create_dbfile() {
    [ -z "$1" ] && die "create_dbfile():" Missing arguments;
    check_params || die "create_dbfile():" Missing parameters;

    . $pzonedir/$1/config	# Load zone global/SOA parameters
    . $pzonedir/$1/serial	# Read zone serial number

    local output=$binddir/db.$1
    [ -n "$2" ] && output=$2

    cat >$output <<EOF
;
; BIND data file for $1 - DB description
; Created by $me on $(date -R)
;
\$TTL	$ttl	; ($(human $ttl))
@	IN	SOA	$ns. $admin. (
		$(printf "%10d ; Serial" $serial)
		$(printf "%10d ; Refresh (%s)" $refresh $(human $refresh))
		$(printf "%10d ; Retry (%s)" $retry $(human $retry))
		$(printf "%10d ; Expire (%s)" $expire $(human $expire))
		$(printf "%10d ; Negative Cache TTL (%s)" $ncachettl $(human $ncachettl))
);
EOF

    for type in ${supported_records[*]}; do
	[ -f "$pzonedir/$1/records.$type" ] || continue;
	echo -e ";\n; Record(s)" $type >> $output
	sort $pzonedir/$1/records.$type | awk -F, \
	    '{print $1"\tIN\t'$type'\t"$2" "$3;}' >> $output
    done

    cat >>$output <<EOF
;
; End of file: $binddir/db.$1
;
EOF
    return 0;
}

## Input: Zone name {Output file}
## Return: true
function create_zonefile() {
    [ -z "$1" ] && die "create_zonefile():" Missing arguments;
    local output=$binddir/zone.$1
    [ -n "$2" ] && output=$2

    . $pzonedir/$1/config	# Load zone global parameters

    cat >$output <<EOF
;
; BIND data file for $1 - zone description
; Created by $me on $(date -R)
;
zone "$1" {
	type $type;
	file "$binddir/db.$1";
};

// No reverse resolution for $1
EOF
    cat >>$output <<EOF
;
; End of file: $binddir/zone.$1
;
EOF

    return 0;
}

## Input: Zone name
## Return: true
function disable_zone() {
    [ -z "$1" ] && die "disable_zone():" Missing arguments;

    [ -f "$binddir/named.conf.local" ] || \
	die "disable_zone(): File not found:" $binddir/named.conf.local;

    sed -i '/include.*zone.$1/d' $binddir/named.conf.local;

    ## Delete 'backups'
    [ -f "$binddir/db.$1.disabled" ]	&& rm -f $binddir/db.$1.disabled;
    [ -f "$binddir/zone.$1.disabled" ]	&& rm -f $binddir/zone.$1.disabled;

    ## Create 'backups'
    mv $binddir/db.$1	$binddir/db.$1.disabled
    mv $binddir/zone.$1 $binddir/zone.$1.disabled

    cat <<EOF
Zone $1 disabled.

You still need to restart bind service:
#> service bind9 restart
EOF

    return 0
}

## Input: Zone name
## Output: none
## Return: true
function delete_zone() {
    [ -z "$1" ] && die "delete_zone():" Missing arguments;
    [ -f "$binddir/db.$1" ] || [ -f "$binddir/zone.$1" ] \
	&& die Zone activated: $binddir/zone.$1 "\nPlease disable zone first";

    ## Delete 'backups'
    [ -d "$pzonedir/$1.deleted" ] && rm -rf $pzonedir/$1.deleted;

    ## Create 'backups'
    mv $pzonedir/$1	$pzonedir/$1.deleted;

    return 0;
}

## Input: Zone name, Zone admin email {Zone nameserver}
## Output: none
## Return: true
function create_zone() {
    local admin=$2
    local nameserver=$3
    [ -z "$2" ] && die "create_zone():" Missing arguments;
    [ -f "$binddir/db.$1" ] && die Zone already exist: $binddir/db.$1;
    [ -d "$pzonedir/$1" ] && die  Zone already exist: $pzonedir/$1;
    [ -z "$3" ] && nameserver=ns.$1
    mkdir -p $pzonedir/$1
    cat >$pzonedir/$1/config <<EOF
type=master
ns=$nameserver
admin=${admin/@/.}
ttl=$ttl
refresh=$refresh
retry=$retry
expire=$expire
ncachettl=$ncachettl
EOF
    echo "serial="$(date +%Y%m%d01) > $pzonedir/$1/serial

    # Add NS record
    add_record $1 A ns $ipaddr
    add_record $1 NS @ $nameserver

    verbose Zone $1 created.

    return 0;
}

## Input: Zone name
## Return: true
function show_zone() {
    [ -z "$1" ] && die "show_zone():" Missing arguments;
    check_params || die "show_zone():" Missing parameters;
    check_zone $1 || die "show_zone():" Zone not found: $1;

    local tmpfile=$(mktemp)
    create_zonefile $1 $tmpfile;
    cat $tmpfile;
    create_dbfile $1 $tmpfile;
    cat $tmpfile;
    rm -f $tmpfile;

    return 0
}

## Input: Zone name
## Return: true
function publish_zone() {
    [ -z "$1" ] && die "publish_zone():" Missing arguments;
    check_params || die "publish_zone():" Missing parameters;

    [ -f "$binddir/named.conf.local" ] || \
	die "publish_zone(): File not found:" $binddir/named.conf.local;

    create_zonefile $1;
    create_dbfile $1;

    sed -i '/include.*zone.$1/d' $binddir/named.conf.local;
    echo 'include "'$binddir'/zone.'$1'";' >> $binddir/named.conf.local;

    cat <<EOF
Zone $1 published:
-> $binddir/sone.$1
-> $binddir/db.$1

You still need to restart bind service:
#> service bind9 restart

EOF
    return 0
}

# Input: interface name {, IP family (-4|-6)}
# Output: IP address
function getip() {
    ip $2 addr show dev $1 2>/dev/null | \
	grep "scope global" | \
	grep -v "temporary" | \
	head -1 | \
	awk '{ print $2; }' | \
	cut -d '/' -f 1
}

## Input: batch file
## Output: none
## Return: true
function pzone_batch() {
    [ -z "$1" ] && die "pzone_batch():" Missing arguments;
    [ -f "$1" ] || die "File not found:" $1
    local batchfile=$(mktemp);
    local awkfile=$(mktemp);
    cat <<EOF >$awkfile
/create_zone/ { print };
/publish_zone/ { print };
/show_zone/ { print };
/add_record/ { print };
/del_record/ { print };
EOF
    awk -f $awkfile $1 > $batchfile;
    . $batchfile;
    rm -f $batchfile $awkfile;
    return 0;
}

## Input: none
## Output: none
## Return: Does not returm, exit 1.
function usage() {
    cat <<EOF
Usage: $me [<options>] <command> <zonename> [<args>]

Options:
  -h            - print this help.
  -t TTL        - Zone Time-To-Live value (default: $(human $ttl)).
  -r REFRESH    - Zone refresh value (default: $(human $refresh)).
  -e EXPIRE     - Zone expire value (default:  $(human $expire)).
  -n NCACHETTL  - Negative cache TTL value (default: $(human $ncachettl)).
  -f            - Force operation.

Commands:
  help          - Display detailed help.
  create	- Create a new zone for configuration.
  publish	- Publish a zone for immediate handling.
  disable	- Unpublish a zone from bind handling.
  show		- Display bind data file for the zone.
  config	- Configure zone parameters (excl. records)
  add zone	- Add a new zone for configuration (same as create).
  add record	- Add zone record.
  del zone	- Delete a zone.
  del record	- Delete a zone record.
  del records	- Delete all zone records.

EOF
##  batch FILE	- Batch mode, run commands from a script.
	
    [ -z "$1" ] && exit;

cat <<EOF
CREATE A ZONE:
  create ZONENAME ADMINEMAIL [NAMESERVER]
  add zone ZONENAME ADMINEMAIL [NAMESERVER]
	ZONENAME   - Name of the zone to create.
	ADMINEMAIL - Email address of technical contact.
	NAMESERVER - Zone nameserver (optional default to ns.ZONEMAME)

  The command creates a zone in the $me database
  (cfr. $pzonedir/).

PUBLISH A ZONE:
  publish ZONENAME
	ZONENAME   - Name of the zone to publish.

  The command creates and install bind data file from $me zone
  database. You still need to restart the bind service.

DISABLE A ZONE:
  disable ZONENAME
	ZONENAME   - Name of the zone to disable (aka. unpublish).

  The command removes bind data file for the zone. You still need to
  restart the bind service.

DISPLAY A ZONE:
  show ZONENAME
	ZONENAME   - Name of the zone to display.

  The command creates and displays bind data file from $me zone
  database. Files are NOT install, just displayed as it would be
  installed by publish command.

CONFIGURE A ZONE:
  config ZONENAME NAME VALUE
	ZONENAME   - Name of the zone to configure.

  The command set or update zone configuration parameters, such as
  ttl, ns, admin, refresh, retry, expire & n(egative)cachettl

ADD RECORD TO A ZONE:
  add record ZONENAME TYPE NAME PARAMS...
	ZONENAME   - Name of the zone to update.
	TYPE       - Record type (A AAAA MX TXT CNAME)
	NAME       - Record name (eg. www, mail)
	PARAMS     - Record paramters depending from record type
                     MX: PARAMS=MX-Priority mailserver
                         mailserver MUST exists (internal as
                         A(AAA)record or external, hence resolvable)
                     NS & CNAME: PARAMS=host
                         host MUST exists (internal as A(AAA) record
                         or external, hence resolvable)
                     A(AAA): PARAMS=IP Address
                     TXT: PARAMS=Associated TXT value

DELETE A ZONE:
  del zone ZONENAME
	ZONENAME   - Name of the zone to delete.

  The command deletes the zone from the $me database, only of the zone
  is not published. You may need to disable the zone first.

DELETE A ZONE RECORD:
  del record ZONENAME TYPE NAME [PRIORITY]
	ZONENAME   - Name of the zone to update.
	TYPE       - Record type (A AAAA MX TXT CNAME)
	NAME       - Record name (eg. www, mail)
        PRIORITY   - MX record priority, only for MX record.

  The command deletes a zone record from the $me database.

DELETE ALL ZONE RECORDS:
  del records ZONENAME [TYPE]
	ZONENAME   - Name of the zone to update.
	TYPE       - Record type (A AAAA MX TXT CNAME)

  The command deletes all records from all or a given type, if
  specified.

EOF
    exit;
}

## Get (default) IP address
[ -z "$ipaddr" ] && [ -n "$ifname" ] && ipaddr=$(getip $ifname)

# Command line options...
while getopts "hft:r:e:n:i:a:" OPTION; do
    case "$OPTION" in
	t)	ttl=$OPTARG;
	    ;;
	r)	refresh=$OPTARG;
	    ;;
	e)	expire=$OPTARG;
	    ;;
	n)	ncachettl=$OPTARG;
	    ;;
	f)	force=true;
	    ;;
	i)	ipaddr=$(getip $OPTARG);
	    ;;
	a)	ipaddr=$OPTARG;
	    ;;
	h)	usage; 
	    ;;
	\?)
	    warn Invalid option: -$OPTARG
	    usage;
	    ;;
    esac
done
shift $((OPTIND-1))

[ "$1" == "help" ] && usage help;
[ -z "$2" ] && usage;

case $1 in 
    hel*)
	shift; usage $1;
	;;
    cre*)
	shift; create_zone $*;
	;;
    pub*)
	shift; publish_zone $*;
	;;
    dis*)
	shift; disable_zone $*;
	;;
    sho*)
	shift; show_zone $*;
	;;
    con*)
	warn "Command not supported yet: $1";
	exit 1;
	;;
    add)
	shift
	case $1 in
	    zone)
		shift; create_zone $*;
		;;
	    rec*)
		shift; add_record $*;
		;;
	    *)
		warn Unsupported add command type: $1
		exit 1;
		;;
	esac
	;;
    del*)
	shift;
	case $1 in
	    zone)
		shift; delete_zone $*;
		;;
	    *)
		warn Unsupported del command type: $1
		exit 1;
		;;
	esac
	;;
    bat*)
	shift; pzone_batch $1;
	;;
    *)
	warn Unsupported command: $1;
	exit 1;
	;;
esac
exit 0;
